services:
  nestjs-authentication-starterkit:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
      target: deploy
    image: nestjs-authentication-starterkit:latest
    env_file:
      - ../../.env.production.sample
    ports:
      - "3010:3010"
